### ISSUE TITLE
Missing Employees in Internet Explorer 11 

### ISSUE THREAD

**Issue by davidnquach** [Orasi/blue-source#20]
Eric Trout found a bug when he accessed BlueSource through Rural Directory. After clicking the button, he found that he was automatically logged in, even after clearing his cache and browsing history. He's taken to the Employees page but does not see any employees that are directly under him. Even after logging out and logging back in, he still does not see his employees. The bug is not reproducible in chrome.

**Comment by pjthomas45** [comment]
Anymore info on this? Is this fix in staging?
