### ISSUE TITLE
Managers and employees cannot view vacation days in FY2016. 

### ISSUE THREAD

**Issue by adamdthomas** [Orasi/blue-source#27]
For any given employee, You should be able to view any fiscal year that they have time off in. 

![image](https://cloud.githubusercontent.com/assets/5970730/5455489/f1ab780c-8509-11e4-870a-1b06983b9115.png)

Once i leave that screen, i cannot get back to Fiscal year 2016 to view her time off.

**Comment by pjthomas45** [comment]
Working in staging. Closing.
