### ISSUE TITLE
Receiving error while editing employee navigates to logged in employees profile instead of employee that was being editted

### ISSUE THREAD

**Issue by JustinPhlegar** [Orasi/blue-source#45]
Steps to reproduce:
* Go to employee profile who's role requires a department to be assigned, like Upper Management
  http://bluesourcestaging.herokuapp.com/employees/54

* Attempt to remove assigned department

* Modal disappears generating a error box on main Employee page. App has navigated to the logged in employee profile instead of the employee that was being viewed.
* If logged in as Company admin, the displayed page when the error appears is    http://bluesourcestaging.herokuapp.com/employees/1 instead of http://bluesourcestaging.herokuapp.com/employees/54

**Comment by Mattwhooo** [comment]
Thanks Justin.  I've fixed this.  It should always redirect to the employee page being edited now.
