### ISSUE TITLE
Employee Table in Project Details Page

### ISSUE THREAD

**Issue by adamdthomas** [Orasi/blue-source#49]
Emp FName | Emp LName | Lead | Start Date | End Date

**Comment by Mattwhooo** [comment]
Thoughts? 

![image](https://cloud.githubusercontent.com/assets/5597399/8875913/486a424e-31ea-11e5-9034-09cf13fc1005.png)

**Comment by JustinPhlegar** [comment]
Looks good.

Maybe a future enhancement being each name (employee and lead) is a link to the employee or a email client. Additionally, maybe an email project team button where employee leads are CC'ed.

Sent from my Verizon Wireless 4G LTE DROID


Matt Watson <notifications@github.com> wrote:


Thoughts?

[image]<https://cloud.githubusercontent.com/assets/5597399/8875913/486a424e-31ea-11e5-9034-09cf13fc1005.png>

**Comment by Mattwhooo** [comment]
Got the links in place.  I'm a little dubious about the email project team.  What kind of use case are you thinking of?

![image](https://cloud.githubusercontent.com/assets/5597399/8880101/2c66116c-3204-11e5-8bc4-0682f51c5745.png)

**Comment by JustinPhlegar** [comment]
Twas just random thought I had just after downing a mug of coffee.

Looks good.

Sent from my Verizon Wireless 4G LTE DROID


Matt Watson <notifications@github.com> wrote:


Got the links in place. I'm a little dubious about the email project team. What kind of use case are you thinking of?

[image]<https://cloud.githubusercontent.com/assets/5597399/8880101/2c66116c-3204-11e5-8bc4-0682f51c5745.png>

**Comment by Mattwhooo** [comment]
Awesome.  I've got all the 1.4.0 stuff in staging and should be in cert in a few minutes.  Pending approval from everyone we can push this stuff to prod.
