### ISSUE TITLE
Re-Align

### ISSUE THREAD

**Issue by adamdthomas** [Orasi/blue-source#50]
Re align date picker in calendar

![image](https://cloud.githubusercontent.com/assets/5970730/8779654/601d4640-2ed2-11e5-8ab5-1353f0155734.png)

**Comment by Mattwhooo** [comment]
![image](https://cloud.githubusercontent.com/assets/5597399/8857808/febfffd8-3141-11e5-9936-fdc0efe9b454.png)
Approve?

**Comment by Mattwhooo** [comment]
Done and in staging
