### ISSUE TITLE
Expand/Collapse all in calendar

### ISSUE THREAD

**Issue by adamdthomas** [Orasi/blue-source#51]
Maybe use some kick ass giphicons?

![image](https://cloud.githubusercontent.com/assets/5970730/8779690/8d4af2ca-2ed2-11e5-9a4d-2f3ffb20f086.png)

**Comment by Mattwhooo** [comment]
Do you mean this 'Show All' link that already exists and is in your screenshot above?

![image](https://cloud.githubusercontent.com/assets/5597399/8857913/83ce2c7c-3142-11e5-80f4-cadb041f2827.png)

**Comment by Mattwhooo** [comment]
Done and in staging
